# Generated by Django 5.2.7 on 2025-10-04 07:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=api.models.object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('', '')], max_length=10)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('', '')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateOfBirth', models.DateTimeField()),
                ('phone', models.CharField(max_length=50)),
                ('picture', models.URLField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
