# Generated by Django 5.2.7 on 2025-10-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, null=True),
        ),
    ]
